services:
  professionals-for-christ:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shared_local_network

networks:
  shared_local_network:
    external: true
