services:
  pfc-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared_local_network

networks:
  shared_local_network:
    external: true